spring:
  application:
    name: band_schedule
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/band_schedule}
    username: ${DB_USERNAME:band_schedule}
    password: ${DB_PASSWORD:band_schedule}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
