-- =========================================================
-- V1__initial_schema.sql
-- CraneTeamMatching initial schema
-- PostgreSQL / H2 PostgreSQL mode compatible
-- =========================================================


-- =========================================================
-- 1. users
-- =========================================================

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       name VARCHAR(50) NOT NULL,
                       student_number VARCHAR(30) NOT NULL,
                       status VARCHAR(30) NOT NULL,

                       CONSTRAINT uk_users_student_number
                           UNIQUE (student_number),

                       CONSTRAINT ck_users_status
                           CHECK (
                               status IN (
                                          'ACTIVE',
                                          'ON_LEAVE',
                                          'GRADUATED',
                                          'WITHDRAWN'
                                   )
                               )
);


-- =========================================================
-- 2. user_session
--
-- 현재 UserSession Entity에는 @Table이 없기 때문에
-- Hibernate naming strategy 기준 user_session을 사용한다.
-- =========================================================

CREATE TABLE user_session (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              user_id BIGINT NOT NULL,
                              part VARCHAR(30) NOT NULL,

                              CONSTRAINT fk_user_session_user
                                  FOREIGN KEY (user_id)
                                      REFERENCES users(id),

                              CONSTRAINT ck_user_session_part
                                  CHECK (
                                      part IN (
                                               'VOCAL',
                                               'GUITAR',
                                               'BASS',
                                               'DRUM',
                                               'KEYBOARD'
                                          )
                                      )
);

CREATE INDEX idx_user_session_user_id
    ON user_session(user_id);


-- =========================================================
-- 3. performances
-- =========================================================

CREATE TABLE performances (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              title VARCHAR(100) NOT NULL,
                              performance_date DATE NOT NULL,
                              location VARCHAR(100) NOT NULL,

                              schedule_window_start_date DATE,
                              schedule_window_end_date DATE,

                              created_at TIMESTAMP NOT NULL,

                              CONSTRAINT ck_performances_schedule_window_pair
                                  CHECK (
                                      (schedule_window_start_date IS NULL
                                          AND schedule_window_end_date IS NULL)
                                          OR
                                      (schedule_window_start_date IS NOT NULL
                                          AND schedule_window_end_date IS NOT NULL)
                                      ),

                              CONSTRAINT ck_performances_schedule_window_order
                                  CHECK (
                                      schedule_window_start_date IS NULL
                                          OR schedule_window_start_date <= schedule_window_end_date
                                      ),

                              CONSTRAINT ck_performances_schedule_window_before_performance
                                  CHECK (
                                      schedule_window_end_date IS NULL
                                          OR schedule_window_end_date <= performance_date
                                      )
);


-- =========================================================
-- 4. performance_members
-- =========================================================

CREATE TABLE performance_members (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     performance_id BIGINT NOT NULL,
                                     user_id BIGINT NOT NULL,

                                     CONSTRAINT fk_performance_members_performance
                                         FOREIGN KEY (performance_id)
                                             REFERENCES performances(id),

                                     CONSTRAINT fk_performance_members_user
                                         FOREIGN KEY (user_id)
                                             REFERENCES users(id),

                                     CONSTRAINT uk_performance_members_performance_user
                                         UNIQUE (performance_id, user_id)
);

CREATE INDEX idx_performance_members_user_id
    ON performance_members(user_id);


-- =========================================================
-- 5. performance_confirmed_songs
-- =========================================================

CREATE TABLE performance_confirmed_songs (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                             performance_id BIGINT NOT NULL,

                                             song VARCHAR(200) NOT NULL,
                                             admin_memo VARCHAR(1000),

                                             created_at TIMESTAMP NOT NULL,

                                             CONSTRAINT fk_performance_confirmed_songs_performance
                                                 FOREIGN KEY (performance_id)
                                                     REFERENCES performances(id)
);

CREATE INDEX idx_performance_confirmed_songs_performance_id
    ON performance_confirmed_songs(performance_id);


-- =========================================================
-- 6. teams
-- =========================================================

CREATE TABLE teams (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       performance_id BIGINT NOT NULL,

                       name VARCHAR(100) NOT NULL,

    -- 팀 생성 시 아직 곡이 확정되지 않을 수 있음
                       confirmed_song VARCHAR(200),

                       CONSTRAINT fk_teams_performance
                           FOREIGN KEY (performance_id)
                               REFERENCES performances(id)
);

CREATE INDEX idx_teams_performance_id
    ON teams(performance_id);


-- =========================================================
-- 7. team_members
-- =========================================================

CREATE TABLE team_members (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              team_id BIGINT NOT NULL,
                              performance_member_id BIGINT NOT NULL,

                              part VARCHAR(30) NOT NULL,

                              CONSTRAINT fk_team_members_team
                                  FOREIGN KEY (team_id)
                                      REFERENCES teams(id),

                              CONSTRAINT fk_team_members_performance_member
                                  FOREIGN KEY (performance_member_id)
                                      REFERENCES performance_members(id),

                              CONSTRAINT uk_team_members_team_performance_member
                                  UNIQUE (team_id, performance_member_id),

                              CONSTRAINT ck_team_members_part
                                  CHECK (
                                      part IN (
                                               'VOCAL',
                                               'GUITAR',
                                               'BASS',
                                               'DRUM',
                                               'KEYBOARD'
                                          )
                                      )
);

CREATE INDEX idx_team_members_performance_member_id
    ON team_members(performance_member_id);


-- =========================================================
-- 8. input_links
-- =========================================================

CREATE TABLE input_links (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             token VARCHAR(64) NOT NULL,

                             performance_id BIGINT NOT NULL,

                             type VARCHAR(50) NOT NULL,

                             active BOOLEAN NOT NULL,

                             expires_at TIMESTAMP,
                             created_at TIMESTAMP NOT NULL,

                             CONSTRAINT uk_input_links_token
                                 UNIQUE (token),

                             CONSTRAINT fk_input_links_performance
                                 FOREIGN KEY (performance_id)
                                     REFERENCES performances(id),

                             CONSTRAINT ck_input_links_type
                                 CHECK (
                                     type IN (
                                              'SONG_REQUEST',
                                              'SONG_VOTE',
                                              'SONG_PREFERENCE',
                                              'AVAILABLE_TIME',
                                              'FINAL_SCHEDULE_VIEW'
                                         )
                                     )
);

CREATE INDEX idx_input_links_performance_id
    ON input_links(performance_id);


-- =========================================================
-- 9. song_requests
-- =========================================================

CREATE TABLE song_requests (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               performance_id BIGINT NOT NULL,

    -- 공연 단위 희망곡이면 team이 없을 수 있음
                               team_id BIGINT,

                               requested_by_member_id BIGINT NOT NULL,

                               song VARCHAR(200) NOT NULL,

                               youtube_url VARCHAR(500),

                               created_at TIMESTAMP NOT NULL,

                               CONSTRAINT fk_song_requests_performance
                                   FOREIGN KEY (performance_id)
                                       REFERENCES performances(id),

                               CONSTRAINT fk_song_requests_team
                                   FOREIGN KEY (team_id)
                                       REFERENCES teams(id),

                               CONSTRAINT fk_song_requests_requested_by_member
                                   FOREIGN KEY (requested_by_member_id)
                                       REFERENCES performance_members(id)
);

CREATE INDEX idx_song_requests_performance_id
    ON song_requests(performance_id);

CREATE INDEX idx_song_requests_team_id
    ON song_requests(team_id);

CREATE INDEX idx_song_requests_requested_by_member_id
    ON song_requests(requested_by_member_id);


-- =========================================================
-- 10. song_votes
-- =========================================================

CREATE TABLE song_votes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            song_request_id BIGINT NOT NULL,
                            voter_member_id BIGINT NOT NULL,

                            vote VARCHAR(30) NOT NULL,

                            reason VARCHAR(500),

                            CONSTRAINT fk_song_votes_song_request
                                FOREIGN KEY (song_request_id)
                                    REFERENCES song_requests(id),

                            CONSTRAINT fk_song_votes_voter_member
                                FOREIGN KEY (voter_member_id)
                                    REFERENCES performance_members(id),

    -- 같은 사람이 같은 희망곡에 여러 번 투표하는 것 방지
                            CONSTRAINT uk_song_votes_request_voter
                                UNIQUE (song_request_id, voter_member_id),

                            CONSTRAINT ck_song_votes_vote
                                CHECK (
                                    vote IN (
                                             'POSSIBLE',
                                             'IMPOSSIBLE',
                                             'HOLD'
                                        )
                                    )
);

CREATE INDEX idx_song_votes_voter_member_id
    ON song_votes(voter_member_id);


-- =========================================================
-- 11. song_preferences
-- =========================================================

CREATE TABLE song_preferences (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  performance_confirmed_song_id BIGINT NOT NULL,
                                  performance_member_id BIGINT NOT NULL,

                                  rank INTEGER NOT NULL,

                                  CONSTRAINT fk_song_preferences_confirmed_song
                                      FOREIGN KEY (performance_confirmed_song_id)
                                          REFERENCES performance_confirmed_songs(id),

                                  CONSTRAINT fk_song_preferences_performance_member
                                      FOREIGN KEY (performance_member_id)
                                          REFERENCES performance_members(id),

                                  CONSTRAINT uk_song_preferences_song_member
                                      UNIQUE (
                                              performance_confirmed_song_id,
                                              performance_member_id
                                          ),

                                  CONSTRAINT ck_song_preferences_rank
                                      CHECK (rank >= 1)
);

CREATE INDEX idx_song_preferences_performance_member_id
    ON song_preferences(performance_member_id);


-- =========================================================
-- 12. performance_setlist_items
-- =========================================================

CREATE TABLE performance_setlist_items (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                           performance_id BIGINT NOT NULL,
                                           team_id BIGINT NOT NULL,

                                           sequence_number INTEGER NOT NULL,

                                           CONSTRAINT fk_setlist_items_performance
                                               FOREIGN KEY (performance_id)
                                                   REFERENCES performances(id),

                                           CONSTRAINT fk_setlist_items_team
                                               FOREIGN KEY (team_id)
                                                   REFERENCES teams(id),

    -- 한 공연에서 같은 팀이 두 번 등장하는 것 방지
                                           CONSTRAINT uk_setlist_items_performance_team
                                               UNIQUE (performance_id, team_id),

    -- 한 공연에서 같은 순번이 두 번 등장하는 것 방지
                                           CONSTRAINT uk_setlist_items_performance_sequence
                                               UNIQUE (performance_id, sequence_number),

                                           CONSTRAINT ck_setlist_items_sequence
                                               CHECK (sequence_number >= 1)
);

CREATE INDEX idx_setlist_items_team_id
    ON performance_setlist_items(team_id);


-- =========================================================
-- 13. available_time
--
-- 현재 Entity @Table(name = "available_time") 기준
-- =========================================================

CREATE TABLE available_time (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                team_member_id BIGINT NOT NULL,

                                start_date_time TIMESTAMP NOT NULL,
                                end_date_time TIMESTAMP NOT NULL,

                                CONSTRAINT fk_available_time_team_member
                                    FOREIGN KEY (team_member_id)
                                        REFERENCES team_members(id),

                                CONSTRAINT ck_available_time_range
                                    CHECK (start_date_time < end_date_time)
);

CREATE INDEX idx_available_time_team_member_id
    ON available_time(team_member_id);


-- =========================================================
-- 14. final_schedules
-- =========================================================

CREATE TABLE final_schedules (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 team_id BIGINT NOT NULL,

                                 start_date_time TIMESTAMP NOT NULL,
                                 end_date_time TIMESTAMP NOT NULL,

                                 memo VARCHAR(1000),

                                 CONSTRAINT fk_final_schedules_team
                                     FOREIGN KEY (team_id)
                                         REFERENCES teams(id),

                                 CONSTRAINT ck_final_schedules_range
                                     CHECK (start_date_time < end_date_time)
);

CREATE INDEX idx_final_schedules_team_id
    ON final_schedules(team_id);

-- FinalScheduleService의 전역 합주실 충돌 조회 보조용
CREATE INDEX idx_final_schedules_time_range
    ON final_schedules(start_date_time, end_date_time);