CREATE TABLE clubs (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       admin_token VARCHAR(36) NOT NULL,
                       created_at TIMESTAMP NOT NULL,

                       CONSTRAINT uk_clubs_admin_token
                           UNIQUE (admin_token)
);

ALTER TABLE users
    ALTER COLUMN student_number TYPE VARCHAR(8);

ALTER TABLE users
    ADD CONSTRAINT ck_users_student_number_format
        CHECK (student_number ~ '^[0-9]{8}$');

ALTER TABLE performances
    ADD COLUMN club_id BIGINT NOT NULL;

ALTER TABLE performances
    ADD CONSTRAINT fk_performances_club
        FOREIGN KEY (club_id)
            REFERENCES clubs(id);

CREATE INDEX idx_performances_club_id
    ON performances(club_id);
