CREATE TABLE member_access_sessions (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        token VARCHAR(128) NOT NULL,

                                        performance_member_id BIGINT NOT NULL,
                                        input_link_id BIGINT NOT NULL,

                                        expires_at TIMESTAMP NOT NULL,
                                        created_at TIMESTAMP NOT NULL,

                                        CONSTRAINT uk_member_access_sessions_token
                                            UNIQUE (token),

                                        CONSTRAINT fk_member_access_sessions_performance_member
                                            FOREIGN KEY (performance_member_id)
                                                REFERENCES performance_members(id),

                                        CONSTRAINT fk_member_access_sessions_input_link
                                            FOREIGN KEY (input_link_id)
                                                REFERENCES input_links(id)
);

CREATE INDEX idx_member_access_sessions_performance_member_id
    ON member_access_sessions(performance_member_id);

CREATE INDEX idx_member_access_sessions_input_link_id
    ON member_access_sessions(input_link_id);
